export { default as Attended} from "./Attended"
export { default as BookPublication } from "./BookPublication"
export { default as CertificateCourses } from "./CertificateCourses"
export { default as ConfeSeminar } from "./ConfeSeminar"
export { default as ConsultancyReport } from "./ConsultancyReport"
export { default as Contribution } from "./Contribution"
export { default as ExtensionActivity } from "./ExtensionActivity"
export { default as FacultyAchievements } from "./FacultyAchievements"
export { default as FacultyConferencePublication } from "./FacultyConferencePublication"
export { default as FacultyExchange } from "./FacultyExchange"
export { default as FacultyResource } from "./FacultyResource"
export { default as Grants } from './Grants'
export { default as IndustrialVisits } from "./IndustrialVisits"
export { default as PatentPublication } from "./PatentPublication"
export { default as ProfessionalAffiliations } from "./ProfessionalAffiliations"
export { default as Research } from "./Research"
export { default as TechnicalCompetitions } from "./TechnicalCompetitions"
export { default as WebinarConducted } from "./WebinarConducted"